global:
  scrape_interval: 2s

scrape_configs: 
  - job_name: 'core_service'
    static_configs:
      - targets: ['localhost:8080'] # Core service metrics

  - job_name: 'auth_service'
    static_configs:
      - targets: ['localhost:8081'] # Auth service metrics

  - job_name: 'fileserver_service'
    static_configs:
      - targets: ['localhost:8082'] # Fileserver service metrics